### PR TITLE
Add alert code for "message" type

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #66. No changes are needed on the layout layouts/joomla/system/message.php. But default messages do come in with the type message which is not recognized by bootstrap. This pr adds an alert type message to the template.

To test this add the following code somewhere in a file where it gets executed on the frontpage like components/com_content/content.php after line 13:
`JFactory::getApplication()->enqueueMessage('Demo message');`

### CODE REVIEW

**Comment by zero-24** [comment]
We should use something like:

```
.alert-message {
  @include alert-variant($alert-success-bg, $alert-success-border, $alert-success-text);
}
.alert-error {
  @include alert-variant($alert-danger-bg, $alert-danger-border, $alert-danger-text);
}
.alert-notice {
  @include alert-variant($alert-info-bg, $alert-info-border, $alert-info-text);
}
```

as message is green currently in protostar.

see: https://docs.joomla.org/Display_error_messages_and_notices

To test:
```php
// Green
JFactory::getApplication()->enqueueMessage('Demo message');
// blue
JFactory::getApplication()->enqueueMessage('Demo message', 'notice');
// yellow
JFactory::getApplication()->enqueueMessage('Demo message', 'warning');
// red
JFactory::getApplication()->enqueueMessage('Demo message', 'error');
```

but that result into:

image

what did i broken?

**Comment by laoneo** [comment]
But would it then not make sense to transform the correct alert types in a bs3 layout to the bs alerts? Otherwise every template needs to add that code.

**Comment by zero-24** [comment]
So we need to map.

`message` => `success`
`error` => `danger`
`notice` => `info`

**Comment by laoneo** [comment]
Last commit should do the conversion correct now. Can you please retest and if it is working, please merge it. Thanks.

**Comment by zero-24** [comment]
Works here with the example code above.

**Pull request merged**
