### PR TITLE
Basic template structure and style

### PR DESCRIPTION
**Pull request by cpfeifer**
Pull Request for Issue # .

### Summary of Changes
index.php: a minimal HTML5 layout and jdoc includes
templateDetails.xml: header, navigation & footer module positions
templateDetails.xml: Added style fieldset with one color chooser and header font family text input
Language file string update for style fieldset name
template.scss: minimal structure styling and basic implementation of backend controls

This PR is intended to provide a basic foundation for further collaboration and development. The HTML contains only basic required elements. The backend interface has 2 basic controls, primarily to create and test interaction between the front and back end.

This could not be made much lighter without excluding essential Joomla functionality. I hope we can agree most users of any type will require most of what is here in most cases. It's a basic start we can build on and nothing more.

### Testing Instructions
Publish a module in the each of the Tauristar header, navigation and footer positions. Module chrome can be set in the advanced tab of the module settings.

Color Value in the backend interface sets the hyperlink color and the section border color

Font font family text input controls all top level headings (h1-h6). Defaults to "inherit", accepts a text string for a font name, or font stack.
**Examples:** 
- Arial 
- monospace
- Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif

### Documentation Changes Required
None yet

### CODE REVIEW

**Comment by laoneo** [comment]
I guess you deleted the whole installation folder. The PR is quite big.

**Comment by cpfeifer** [comment]
@laoneo My apologies, I'm still learning git. I thought there was something strange happening, but I'm still learning how this works so I wasn't sure.

It's only 4 files total with minimal changes, is there an easy way to fix the PR? Or what's the best way?

**Comment by laoneo** [comment]
You should also do your changes in a new branch and not the default one, which is in our case tpl_tauristar. I suggest you close this one and create a new one. Everybody goes trough this at the beginning :smile:

**Comment by cpfeifer** [comment]
@laoneo - gotcha. Thanks, I'll try again tomorrow :)

**Pull request closed without merging**
